# Generated by Django 5.0.3 on 2024-04-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(help_text='Enter the delivery address', max_length=200)),
                ('delivery_time', models.DateTimeField(help_text='Enter the delivery time')),
            ],
        ),
    ]
