# Generated by Django 5.0.3 on 2024-04-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='company_name',
            field=models.CharField(default='Packers&co', help_text='Enter the company name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_person_name',
            field=models.CharField(default='kumar', help_text='Enter the delivery person name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Enter the item price', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(default='packing', help_text='Enter the status of the delivery', max_length=20),
            preserve_default=False,
        ),
    ]
