# Generated by Django 5.0.3 on 2024-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliapp', '0002_delivery_company_name_delivery_delivery_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Specify if the delivery is paid or not'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sender_address',
            field=models.CharField(default='Nmit,yelahanka,Bengaluru 560064', help_text='Enter the sender address', max_length=200),
            preserve_default=False,
        ),
    ]
